### ISSUE TITLE
Cannot open or write to gpio from container

### ISSUE THREAD

**Issue by hreidar** [distribrewed/workers#1]
2017-11-09 23:28:49,012 workers.devices.device              WARNING Unable to find/open "/sys/class/gpio/gpio17/value"
Exception in thread ssr:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/project/workers/devices/device.py", line 59, in run
    self.run_cycle()
  File "/opt/project/workers/devices/ssr.py", line 75, in run_cycle
    self.set_ssr_state(False)
  File "/opt/project/workers/devices/ssr.py", line 51, in set_ssr_state
    fo = open(self.io, mode='w')
PermissionError: [Errno 13] Permission denied: '/sys/class/gpio/gpio17/value'

**Comment by hreidar** [comment]
If I docker exec into the container I see the file and I can write to it. It seems that the distribrewed user that is running the python code is not able to access this file, even if the container has a privileged flag.
